### ISSUE TITLE
Functioning in map editor

### ISSUE THREAD

**Issue by modo-lv** [raiguard/Factorio-RecipeBook#49] opened 2021-03-15 19:39 UTC
#### Is your feature request related to a problem? Please describe.

Recipe Book is unavailable in map editor due to there being no player, but would be very helpful when using map editor to plan base layout.

#### Describe the solution you'd like

Recipe Book working in map editor.

#### Additional context

I often use map editor to plan large-scale base layouts, since its a lot easier to modify and move around large areas. Especially in more complicated mods like Nullius, BA or pY, where large-scale planning is essential. Unfortunately, I have no access to recipe information (which, combined with the common practice of hiding non-hand-craftable recipes from player inventory), forcing me to either use some other mod such as FNEI, or keep swapping back and forth between game and map editor while trying to keep recipe info in memory.

**Comment by raiguard** [comment] 2021-03-15 19:40
Uh, it works just fine in the map editor.

**Comment by modo-lv** [comment] 2021-03-15 19:42
Huh, that's weird. I just get the message "Cannot open recipe book yet, please wait etc.", but the book never becomes available. I also tried the `refresh-player-data` command, which also did nothing. I keep getting the message and no recipe book.

**Comment by raiguard** [comment] 2021-03-15 19:43
If you have an enormous modpack installed, it will take a while. Try going into the map settings and turning up the Factorio Library's "translations per tick" value. That will use significantly more UPS but the book should become available a lot faster.

**Comment by modo-lv** [comment] 2021-03-15 19:46
But in regular game it loads in a couple seconds. The problem only exists in map editor.

As for mods, the ones affecting recipes are Nullius + the couple mods that it's compatible with. The rest are QoL stuff that doesn't affect any recipes.

**Comment by modo-lv** [comment] 2021-03-15 19:53
This is what it looks like in map editor:
![image](https://user-images.githubusercontent.com/731551/111212752-ad308380-85d8-11eb-9448-9dbf84f66c4a.png)

And this is in regular new game:
![image](https://user-images.githubusercontent.com/731551/111212864-d224f680-85d8-11eb-9dcb-89053cacbfb0.png)

**Comment by raiguard** [comment] 2021-03-15 20:20
Could you send me your save file so I can take a look?

**Comment by modo-lv** [comment] 2021-03-15 21:23
This is my active game, which I convert to map editor scenario whenever I want to plan the next expansion or layout change. [Nullius.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6144609/Nullius.zip)

**Comment by raiguard** [comment] 2021-03-15 21:29
This is tangential to this problem, but why not just use `/editor` instead of converting it to a scenario?

**Comment by modo-lv** [comment] 2021-03-16 13:39
I simply wasn't aware of the command, thanks, I'll try that!

**Comment by raiguard** [comment] 2021-03-24 17:36
Does using `/editor` work around the problem?

**Comment by modo-lv** [comment] 2021-03-24 18:46
It does.

**Comment by raiguard** [comment] 2021-03-24 20:30
I converted a save to a scenario and loaded it up, but still can't reproduce whatever was happening. Since `/editor` works (and is much easier), I'll just close this issue. Thanks!

**Closed by raiguard** 2021-03-24 20:30 UTC
Labels: bug
