### ISSUE TITLE
Annoying crash, love your mod!

### ISSUE THREAD

**Issue by dacendoran** [raiguard/Factorio-RecipeBook#15] opened 2020-06-11 17:38 UTC
![image](https://user-images.githubusercontent.com/29506995/84420888-ba06ed80-abe8-11ea-9b4c-5267fb9b5484.png)

**Comment by raiguard** [comment] 2020-06-11 19:12
Duplicate of #13, and I actually already released a patch to fix this literally a few minutes before you posted. :D

**Closed by raiguard** 2020-06-11 19:12 UTC

**Comment by dacendoran** [comment] 2020-06-12 00:44
pog, thank you.
