### ISSUE TITLE
Crash on start up 

### ISSUE THREAD

**Issue by GeneralTanker** [raiguard/Factorio-RecipeBook#85] opened 2021-11-17 05:34 UTC
Mod crash on loading save 

To Reproduce

1)Update mods in save to latest version
2)Load save 
3) Crash  

Name : GeneralTank

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/7552013/factorio-current.log)

https://www.dropbox.com/s/21j81ja76l51wd6/Krastorio2%20SE7%2064%20K2%201.2.zip?dl=0

**Comment by rdenison** [comment] 2021-11-17 05:47
I had this same crash. crash log was this:

`Error while running event RecipeBook::on_string_translated (ID 151)
__RecipeBook__/scripts/formatter.lua:61: attempt to concatenate local 'inner' (a nil value)
stack traceback:
	__RecipeBook__/scripts/formatter.lua:61: in function 'rich_text'
	__RecipeBook__/scripts/formatter.lua:271: in function 'get_base_tooltip'
	__RecipeBook__/scripts/formatter.lua:525: in function <__RecipeBook__/scripts/formatter.lua:493>
	(...tail calls...)
	__RecipeBook__/scripts/gui/util.lua:94: in function 'update_list_box'
	__RecipeBook__/scripts/gui/search/root.lua:220: in function 'update_favorites'
	__RecipeBook__/scripts/gui/search/root.lua:166: in function 'build'
	__RecipeBook__/control.lua:471: in function <__RecipeBook__/control.lua:448>`

I think it was caused by the grappling gun mod changing the recipe for the ammo. I updated Aircraft, better cargo planes, grappling gun, LTN, LTN Manager, SE, SE Graphics 1.

**Comment by GeneralTanker** [comment] 2021-11-17 17:52
Look like Raiguard broke something with the update to Factorio Library downgrading it fixes the issue.

**Comment by raiguard** [comment] 2021-11-17 22:51
![image](https://user-images.githubusercontent.com/3515394/142295102-fe424c3c-9894-419a-8fd8-c6d0a46ad71c.png)

I can't get it to load. Could you package and send me these two mods so I can reproduce this?

![image](https://user-images.githubusercontent.com/3515394/142295153-7953c65b-f267-4957-8de9-aaef4e8513bf.png)

**Comment by dgattey** [comment] 2021-11-17 23:23
Also breaking for me when I tried to upgrade to latest version of LTN, LTN Manager, and flib at the same time. Recipe Book is already updated prior to this. 

```
The mod Recipe Book (3.2.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_string_translated (ID 151)
__RecipeBook__/scripts/formatter.lua:61: attempt to concatenate local 'inner' (a nil value)
stack traceback:
	__RecipeBook__/scripts/formatter.lua:61: in function 'rich_text'
	__RecipeBook__/scripts/formatter.lua:271: in function 'get_base_tooltip'
	__RecipeBook__/scripts/formatter.lua:525: in function <__RecipeBook__/scripts/formatter.lua:493>
	(...tail calls...)
	__RecipeBook__/scripts/formatter.lua:121: in function '?'
	__RecipeBook__/scripts/formatter.lua:336: in function 'get_tooltip_deets'
	__RecipeBook__/scripts/formatter.lua:541: in function <__RecipeBook__/scripts/formatter.lua:493>
	(...tail calls...)
	__RecipeBook__/scripts/gui/util.lua:94: in function 'update_list_box'
	__RecipeBook__/scripts/gui/search/root.lua:220: in function 'update_favorites'
	__RecipeBook__/scripts/gui/search/root.lua:166: in function 'build'
	__RecipeBook__/control.lua:471: in function <__RecipeBook__/control.lua:448>
```

**Comment by dgattey** [comment] 2021-11-17 23:29
But I can confirm that the diff fixed it - but obviously the name is wrong now 
![image](https://user-images.githubusercontent.com/982182/142298834-56df9ffb-fab7-44bb-9dbb-9b4a2c99d249.png)

**Comment by raiguard** [comment] 2021-11-17 23:36
@dgattey Could you send me your save file?

**Comment by dgattey** [comment] 2021-11-18 00:23
https://www.icloud.com/iclouddrive/0HZMzuKYDCtgGOoCWo0RaVKCA

Here ya go, it's big + has lots of mods enabled. I saved after using my local version of this mod with your diff applied, so it may not still crash when opened with the current prod version of the mod, not sure.

**Comment by fljsky** [comment] 2021-11-18 01:08
I'm using this mod with K2 and space exploration,but get some crash issue.

 seems like some item without translation will cause this mod try to concatenate with a nil value.

 fallback to internal name insead of player_data.translations[class][name] in  scripts\formatter.lua line:268 maybe solve this problem.

**Comment by kryojenik** [comment] 2021-11-18 02:35
> Look like Raiguard broke something with the update to Factorio Library downgrading it fixes the issue.

I can confirm this finding.  I am getting the same crashes, but reverting flib from 9.1 -> 9.0 resolves the issue.

**Comment by kryojenik** [comment] 2021-11-18 04:02
I have a couple of saves - new games with limited mods:
https://drive.google.com/drive/folders/1YDz1rmqp85Yq92dEwX12KSrUiOJvnqff?usp=sharing

LTN 1.16.7
Recipe Book 3.2.1
flib 0.9.1

LTN Manager 0.3.11 (NoCrash)
LTN Manager 4.0 (Crash)

There seems to be an interaction (at least) with the combination of LTN Manager 4.0 (and above), flib 0.9.1 and Recipe Book (tested with 3.1.5, 3.2.0, and 3.2.1).  And maybe this is more of an issue with LTN Manager than Recipe Book.

Since LTN Manager >= 4.0 depends on flib 0.9.1, reverting to 0.9.0 disabled LTN Manager in my earlier test -- thus no more crashing.

There may be more interactions with other mods, or maybe even some paths to crash with LTN Manager 0.3.11...  I didn't test much past this specific repro.

Loading either of these synced save games should succeed.  Even opening LTM Manager works.   Open Recipe Book in the "Crash" save works.  Once you try to search for something it will crash.

With flib 0.9.1 and LTN Manager 4.0, Recipe Book 3.1.5:
The mod Recipe Book (3.1.5) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_tick (ID 0)
__RecipeBook__/scripts/formatter.lua:48: attempt to concatenate local 'inner' (a nil value)
stack traceback:
	__RecipeBook__/scripts/formatter.lua:48: in function 'rich_text'
	__RecipeBook__/scripts/formatter.lua:276: in function 'get_base_tooltip'
	__RecipeBook__/scripts/formatter.lua:518: in function <__RecipeBook__/scripts/formatter.lua:484>
	(...tail calls...)
	__RecipeBook__/scripts/gui/search/actions.lua:220: in function '?'
	__RecipeBook__/scripts/gui/search/index.lua:11: in function 'handle_action'
	__RecipeBook__/control.lua:175: in function 'handle_gui_action'
	__RecipeBook__/control.lua:360: in function <__RecipeBook__/control.lua:353>

With flib 0.9.1 and LTN Manager 4.0, Recipe Book 3.2.1:
The mod Recipe Book (3.2.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_tick (ID 0)
__RecipeBook__/scripts/formatter.lua:61: attempt to concatenate local 'inner' (a nil value)
stack traceback:
	__RecipeBook__/scripts/formatter.lua:61: in function 'rich_text'
	__RecipeBook__/scripts/formatter.lua:290: in function 'get_base_tooltip'
	__RecipeBook__/scripts/formatter.lua:525: in function <__RecipeBook__/scripts/formatter.lua:493>
	(...tail calls...)
	__RecipeBook__/scripts/gui/search/actions.lua:223: in function '?'
	__RecipeBook__/scripts/gui/search/index.lua:11: in function 'handle_action'
	__RecipeBook__/control.lua:183: in function 'handle_gui_action'
	__RecipeBook__/control.lua:426: in function <__RecipeBook__/control.lua:419>

**Comment by raiguard** [comment] 2021-11-18 05:14
Oh... oh no.
OH NO.

![image](https://user-images.githubusercontent.com/3515394/142356037-26545878-4f90-4e75-bab0-86338797ea7a.png)

I know exactly why this is happening. The dictionary module in flib is not properly handling multiple mods using it at once. LTN Manager's dictionaries are leaking into Recipe Book and vice versa!

Hopefully this won't be hard to fix. I'm just mad at myself more than anything.

**Comment by raiguard** [comment] 2021-11-18 05:25
Well, that was actually pretty easy. A new version of flib will be released shortly that will fix this issue!

**Closed by raiguard** 2021-11-18 05:25 UTC
Labels: bug
