### ISSUE TITLE
Crash occurs when loading a few weeks old savefile after updating mods and having 3 specific mods enabled

### ISSUE THREAD

**Issue by eggpa** [raiguard/Factorio-RecipeBook#94] opened 2022-01-07 15:58 UTC
#### Describe the Bug

I have updated mods to the newest versions and tried to load my savefile, however, the game has crashed.

Disabling `Krastorio 2` or `Even Distribution` or `Recipe Book` mod fixes the issue - crash occurs only when all three are enabled, therefore I'm not sure whether this is a problem with `Recipe Book` or another mod.

#### To Reproduce

1. Install and enable the following mods:
```
Even Distribution 1.0.10
Factorio Library 0.9.2
Krastorio 2 1.2.13
Krastorio 2 Assets 1.1.0
Recipe Book 3.2.2
```
2. Load provided savefile (do not sync mods)
3. The following crash should occur:
```
The mod Krastorio 2 (1.2.13) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event Krastorio2::on_configuration_changed
The mod Recipe Book (3.2.2) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_force_created (ID 28)
__RecipeBook__/scripts/recipe-book.lua:89: attempt to index field 'technology' (a nil value)
stack traceback:
	__RecipeBook__/scripts/recipe-book.lua:89: in function 'handle_research_updated'
	__RecipeBook__/scripts/recipe-book.lua:136: in function 'check_force'
	__RecipeBook__/control.lua:152: in function <__RecipeBook__/control.lua:147>
stack traceback:
	[C]: in function 'create_force'
	__Krastorio2__/scripts/util.lua:5: in function 'ensure_turret_force'
	__Krastorio2__/scripts/migrations.lua:24: in function 'generic'
	__Krastorio2__/control.lua:60: in function <__Krastorio2__/control.lua:58>
```

#### Save file

[krasto.zip](https://github.com/raiguard/Factorio-RecipeBook/files/7829748/krasto.zip)

#### Log file

[factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/7829812/factorio-current.log)

**Comment by raiguard** [comment] 2022-01-08 04:55
Duplicate of #93.

**Closed by raiguard** 2022-01-08 04:55 UTC
Labels: bug
