### ISSUE TITLE
Recipe Book stuck open

### ISSUE THREAD

**Issue by k-sriram** [raiguard/Factorio-RecipeBook#66] opened 2021-08-13 10:37 UTC
#### Describe the Bug

I saved the game with recipe book open, when I reloaded the game it was still open but I am unable to close it.

#### To Reproduce

Unable to reproduce the bug independent of this one occurence. To get the bug in this specific save file, load the game as me and try to close the already open recipebook searcher.

#### Save file & Username

**Save file:** [nullius.zip](https://github.com/raiguard/Factorio-RecipeBook/files/6981747/nullius.zip)

**Username:** redKnightKS

#### Log file

**Log file:**  [factorio-current.log](https://github.com/raiguard/Factorio-RecipeBook/files/6981787/factorio-current.log)

**Comment by raiguard** [comment] 2021-08-13 15:31
Are you on the latest version? This sounds like #60.

**Comment by k-sriram** [comment] 2021-08-13 16:23
I am on version 3.0.2 which is latest on the factorio mod portal currently. But looking through the changelog for 3.0.3 it seems this issue has been fixed. So, I hope the issue will be fixed when the update gets pushed to the mod portal.

**Comment by raiguard** [comment] 2021-08-13 16:59
There is no changelog for 3.0.3, this was fixed in 3.0.2. I'll take a look and see if something is amiss.

**Comment by raiguard** [comment] 2021-08-14 00:54
Well, I can't reproduce this, so I guess case closed? Let me know if it happens to you again.

**Closed by raiguard** 2021-08-14 00:54 UTC
Labels: bug
