### ISSUE TITLE
Crash with back button

### ISSUE THREAD

**Issue by LuziferSenpai** [raiguard/Factorio-RecipeBook#19] opened 2020-06-24 18:03 UTC
Hey,

like I said I crashed your mod, when I clicked WAY to fast the back button. MP has the problem, that when you work in a GUI, it can take a sec or two to really load everything and because your code doesnt test for `back_obj` only for `if back_obj.mod_name and back_obj.gui_name then` it will crash, same will probably go for the next button ;) This is all in the info-base.lua file in line 30.

**Comment by raiguard** [comment] 2020-07-02 15:26
I'll fix this for the redesign. Are there any other places you've found where this can occur?

**Comment by raiguard** [comment] 2020-07-14 03:32
Fixed in the next version.

**Comment by 343N** [comment] 2020-07-21 06:15
after opening the new recipe book (2.0.1), searching, then hitting back, i crash.
` 911.853 Error MainLoop.cpp:1207: Exception at tick 4120635: The mod Recipe Book (2.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_gui_click (ID 1)
__RecipeBook__/scripts/gui/main/base.lua:465: attempt to index field '?' (a nil value)
stack traceback:
	__RecipeBook__/scripts/gui/main/base.lua:465: in function 'open_page'
	__RecipeBook__/scripts/gui/main/base.lua:138: in function 'handler'
	__flib__/gui.lua:352: in function 'dispatch_handlers'
	__flib__/gui.lua:138: in function <__flib__/gui.lua:138>`
World, if needed: Uploading WORLD 23.zip…]()

**Comment by 343N** [comment] 2020-07-21 06:22
The file upload doesn't work for github for some reason, [https://filebin.net/jg0vasny9zkdwy6y/WORLD_23.zip?t=kgm3v1x1](here's an external link for my world).

**Comment by 343N** [comment] 2020-07-21 07:04
on that same world, if I type 'furnace' and change the fuzzy search settings, I get a crash as well (not sure if its worth making another issue about)
```
The mod Recipe Book (2.0.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RecipeBook::on_gui_checked_state_changed (ID 3)
Settings can only be changed by the owning player or the mod that made the setting.
stack traceback:
	__RecipeBook__/scripts/gui/main/pages/settings.lua:23: in function 'handler'
	__flib__/gui.lua:352: in function 'dispatch_handlers'
	__flib__/gui.lua:138: in function <__flib__/gui.lua:138>
stack traceback:
	[C]: in function '__newindex'
	__RecipeBook__/scripts/gui/main/pages/settings.lua:23: in function 'handler'
	__flib__/gui.lua:352: in function 'dispatch_handlers'
	__flib__/gui.lua:138: in function <__flib__/gui.lua:138>
```

**Comment by raiguard** [comment] 2020-07-25 19:11
I'm unable to reproduce the issue with typing `furnace` and changing the fuzzy search setting. Honestly, I don't have any clue as to how that would even happen.

**Closed by raiguard** 2020-07-25 19:11 UTC
Labels: bug
